import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [clientCountryCode, setClientCountryCode] = useState("");
  
  useEffect(() => {
    async function test() {
      const response = await fetch("/api/clientcountry", {
        method: "GET"
      });

      const data = await response.json();

      setClientCountryCode(data.response);
    }

    test();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Test</h1>
        {clientCountryCode ? clientCountryCode : "BR"}
      </main>
    </div>
  )
}

export default Home;

export const getStaticProps: GetStaticProps = async ({ locales }) => {
  

  return {
    props: {}
  }
}
